
const ejs = require("ejs");

/**
 * Report generator
 */
class NowReportGenerator {
  /**
   * 
   * @param {Object} report The JSON report generated by NowLinter
   * @see NowLinter#toJSON()
   */
  constructor(report) {
    this._report = report;
  }

  /**
   * Renders configured report into provided ejs template
   * @param {String} template 
   * @returns {String} rendered template
   */
  toHTML(template) {
    return ejs.render(template, this._report);
  }
}

module.exports = NowReportGenerator;