# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

name: Build Test

on:
  push:
    branches: [ master ]
    paths-ignore: [ "**.md", ".**" ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ "**.md", ".**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 11.x
      uses: actions/setup-node@v1
      with:
        node-version: 11.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
